# Generated by Django 3.2.5 on 2021-07-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('user', '0003_auto_20210708_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='mention_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.listing'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
